#!/usr/bin/env bash

# Make sure to use the *.br_real binary, because buildroot installs a toolchain wrapper that
# does additional path magic we don't want.
exec external/bazel_buildroot_toolchain_files/bin/x86_64-linux-gcc-9.1.0.br_real "$@"
